### ISSUE TITLE
Inconsistency between .gitignore and .gitkeep for application/tasks folder

### ISSUE THREAD

**Issue by aliendrew** [metarhia/Example#227]
.gitignore is supposed to remove /application/tasks from being tracked, but the folder is still tracked because .gitkeep was added there before the .gitignore rule.
The solution is probably to use:
`git rm -r --cached application/tasks`
or remove /application/tasks from .gitignore to continue keeping this folder.

**Comment by tshemsedinov** [comment]
That's how it should be, we do not want to commit task files to git but we need /application/tasks folder
