### ISSUE TITLE
Issue with the response in the Metacom protocol

### ISSUE THREAD

**Issue by slavakaderkin** [metarhia/Example#241]
Metacom doesn't return an array with some objects; it triggers a timeout.

I added a test for Metacom during startup, which calls `api/partner/getPartnersByOffer.js`, but the request is not being processed.

The data for the response is located in `lib/partner/getPartners.js`.

Link to the repository: https://github.com/slavakaderkin/Example

I ran the code on macOS Ventura 13.5.

**Comment by KLarpen** [comment]
Fix was released in Metacom 3.1.0 Currently example project uses impress 3.0.13 that rely on Metacom 3.1.2. It looks like ready to be closed. Am I right, @slavakaderkin ?

**Comment by slavakaderkin** [comment]
Yes, bug was fixed
