### ISSUE TITLE
Error processing url in static directory.

### ISSUE THREAD

**Issue by turone** [metarhia/Example#245]
I created a directory "img" in the static directory, added pictures there. But the file index.html did not create. When i navigate to the \img\ url, the browser waits for the page indefinitely. On the node server it gives an error:
07:52:22  W1   error   unhandledRejection: RangeError [ERR_OUT_OF_RANGE]: The value of "end" is out of range. It must be >= 0 && <= 9007199254740991. Received -1
  new ReadStream (node:internal/fs/streams:201:5)
  Object.createReadStream (node:fs:3060:10)
  Static.serve (\node_modules\impress\lib\static.js:76:32)

**Comment by tshemsedinov** [comment]
Fixed in https://github.com/metarhia/impress/pull/1897
